# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/v1/example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65xample/v1/example.proto\x12\nexample.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x02\n\x07\x45xample\x12\x46\n life_the_universe_and_everything\x18\x01 \x01(\x03R\x1clifeTheUniverseAndEverything\x12/\n\x08\x65xamples\x18\x02 \x03(\x0b\x32\x13.example.v1.ExampleR\x08\x65xamples\x12 \n\njavascript\x18\x03 \x01(\tH\x00R\njavascript\x12\x18\n\x06golang\x18\x04 \x01(\tH\x00R\x06golang\x12>\n\x0f\x61nother_example\x18\x05 \x01(\x0b\x32\x13.example.v1.ExampleH\x00R\x0e\x61notherExample\x12.\n\x04time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x04timeB\x05\n\x03watB\x81\x01\n\x0e\x63om.example.v1B\x0c\x45xampleProtoP\x01Z\x18gen/example/v1;examplev1\xa2\x02\x03\x45XX\xaa\x02\nExample.V1\xca\x02\nExample\\V1\xe2\x02\x16\x45xample\\V1\\GPBMetadata\xea\x02\x0b\x45xample::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.v1.example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016com.example.v1B\014ExampleProtoP\001Z\030gen/example/v1;examplev1\242\002\003EXX\252\002\nExample.V1\312\002\nExample\\V1\342\002\026Example\\V1\\GPBMetadata\352\002\013Example::V1'
  _globals['_EXAMPLE']._serialized_start=74
  _globals['_EXAMPLE']._serialized_end=383
# @@protoc_insertion_point(module_scope)
