# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/v1/oneof.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65xample/v1/oneof.proto\x12\nexample.v1\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc0\x03\n\x05Oneof\x12\x1d\n\tint_stuff\x18\x01 \x01(\x03H\x00R\x08intStuff\x12\x1b\n\x08more_int\x18\x02 \x01(\x03H\x01R\x07moreInt\x12\"\n\x0c\x61nd_more_int\x18\x03 \x01(\x03H\x01R\nandMoreInt\x12$\n\x03wat\x18\x04 \x01(\x0e\x32\x10.example.v1.Wat5H\x01R\x03wat\x12*\n\x05thing\x18\x05 \x01(\x0b\x32\x12.example.v1.Thing5H\x01R\x05thing\x12\x41\n\rthe_timestamp\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01R\x0ctheTimestamp\x12=\n\x0bthe_wrapper\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.BoolValueH\x01R\ntheWrapper\x12\x38\n\nthe_struct\x18\t \x01(\x0b\x32\x17.google.protobuf.StructH\x01R\ttheStruct\x12/\n\x07the_any\x18\n \x01(\x0b\x32\x14.google.protobuf.AnyH\x01R\x06theAnyB\x0b\n\tone_stuffB\x0b\n\tall_stuff\"\x1a\n\x06Thing5\x12\x10\n\x03wat\x18\x02 \x01(\x03R\x03wat**\n\x04Wat5\x12\x14\n\x10WAT5_UNSPECIFIED\x10\x00\x12\x0c\n\x08WAT5_WAT\x10\x01\x42\x7f\n\x0e\x63om.example.v1B\nOneofProtoP\x01Z\x18gen/example/v1;examplev1\xa2\x02\x03\x45XX\xaa\x02\nExample.V1\xca\x02\nExample\\V1\xe2\x02\x16\x45xample\\V1\\GPBMetadata\xea\x02\x0b\x45xample::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.v1.oneof_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016com.example.v1B\nOneofProtoP\001Z\030gen/example/v1;examplev1\242\002\003EXX\252\002\nExample.V1\312\002\nExample\\V1\342\002\026Example\\V1\\GPBMetadata\352\002\013Example::V1'
  _globals['_WAT5']._serialized_start=639
  _globals['_WAT5']._serialized_end=681
  _globals['_ONEOF']._serialized_start=161
  _globals['_ONEOF']._serialized_end=609
  _globals['_THING5']._serialized_start=611
  _globals['_THING5']._serialized_end=637
# @@protoc_insertion_point(module_scope)
