# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/v1/optional.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x65xample/v1/optional.proto\x12\nexample.v1\"\xba\x01\n\x0bOptionalMsg\x12\x1c\n\x07opt_int\x18\x01 \x01(\x03H\x00R\x06optInt\x88\x01\x01\x12\x30\n\x08opt_enum\x18\x02 \x01(\x0e\x32\x10.example.v1.Wat4H\x01R\x07optEnum\x88\x01\x01\x12\x34\n\topt_thing\x18\x03 \x01(\x0b\x32\x12.example.v1.Thing4H\x02R\x08optThing\x88\x01\x01\x42\n\n\x08_opt_intB\x0b\n\t_opt_enumB\x0c\n\n_opt_thing\"\x1a\n\x06Thing4\x12\x10\n\x03wat\x18\x02 \x01(\x03R\x03wat**\n\x04Wat4\x12\x14\n\x10WAT4_UNSPECIFIED\x10\x00\x12\x0c\n\x08WAT4_WAT\x10\x01\x42\x82\x01\n\x0e\x63om.example.v1B\rOptionalProtoP\x01Z\x18gen/example/v1;examplev1\xa2\x02\x03\x45XX\xaa\x02\nExample.V1\xca\x02\nExample\\V1\xe2\x02\x16\x45xample\\V1\\GPBMetadata\xea\x02\x0b\x45xample::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.v1.optional_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016com.example.v1B\rOptionalProtoP\001Z\030gen/example/v1;examplev1\242\002\003EXX\252\002\nExample.V1\312\002\nExample\\V1\342\002\026Example\\V1\\GPBMetadata\352\002\013Example::V1'
  _globals['_WAT4']._serialized_start=258
  _globals['_WAT4']._serialized_end=300
  _globals['_OPTIONALMSG']._serialized_start=42
  _globals['_OPTIONALMSG']._serialized_end=228
  _globals['_THING4']._serialized_start=230
  _globals['_THING4']._serialized_end=256
# @@protoc_insertion_point(module_scope)
