# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/v1/repeated.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x65xample/v1/repeated.proto\x12\nexample.v1\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xe4\x02\n\x08Repeated\x12\x17\n\x07the_int\x18\x01 \x03(\x03R\x06theInt\x12,\n\tthe_enums\x18\x02 \x03(\x0e\x32\x0f.example.v1.WatR\x08theEnums\x12*\n\x07the_msg\x18\x03 \x03(\x0b\x32\x11.example.v1.ThingR\x06theMsg\x12\x41\n\x0ethe_timestamps\x18\x04 \x03(\x0b\x32\x1a.google.protobuf.TimestampR\rtheTimestamps\x12/\n\x08the_anys\x18\x05 \x03(\x0b\x32\x14.google.protobuf.AnyR\x07theAnys\x12\x37\n\x08the_strs\x18\x06 \x03(\x0b\x32\x1c.google.protobuf.StringValueR\x07theStrs\x12\x38\n\x0bthe_structs\x18\x07 \x03(\x0b\x32\x17.google.protobuf.StructR\ntheStructs\"\x19\n\x05Thing\x12\x10\n\x03wat\x18\x02 \x01(\x03R\x03wat*\'\n\x03Wat\x12\x13\n\x0fWAT_UNSPECIFIED\x10\x00\x12\x0b\n\x07WAT_WAT\x10\x01\x42\x82\x01\n\x0e\x63om.example.v1B\rRepeatedProtoP\x01Z\x18gen/example/v1;examplev1\xa2\x02\x03\x45XX\xaa\x02\nExample.V1\xca\x02\nExample\\V1\xe2\x02\x16\x45xample\\V1\\GPBMetadata\xea\x02\x0b\x45xample::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.v1.repeated_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016com.example.v1B\rRepeatedProtoP\001Z\030gen/example/v1;examplev1\242\002\003EXX\252\002\nExample.V1\312\002\nExample\\V1\342\002\026Example\\V1\\GPBMetadata\352\002\013Example::V1'
  _globals['_WAT']._serialized_start=549
  _globals['_WAT']._serialized_end=588
  _globals['_REPEATED']._serialized_start=164
  _globals['_REPEATED']._serialized_end=520
  _globals['_THING']._serialized_start=522
  _globals['_THING']._serialized_end=547
# @@protoc_insertion_point(module_scope)
