# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/v1/simple.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from example.other.v1 import other_pb2 as example_dot_other_dot_v1_dot_other__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65xample/v1/simple.proto\x12\nexample.v1\x1a\x1c\x65xample/other/v1/other.proto\"=\n\x03\x46oo\x12\x36\n\nthis_other\x18\x14 \x01(\x0b\x32\x17.example.other.v1.OtherR\tthisOther*\'\n\x03\x42\x61r\x12\x13\n\x0f\x42\x41R_UNSPECIFIED\x10\x00\x12\x0b\n\x07\x42\x41R_WAT\x10\x01\x42\x80\x01\n\x0e\x63om.example.v1B\x0bSimpleProtoP\x01Z\x18gen/example/v1;examplev1\xa2\x02\x03\x45XX\xaa\x02\nExample.V1\xca\x02\nExample\\V1\xe2\x02\x16\x45xample\\V1\\GPBMetadata\xea\x02\x0b\x45xample::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.v1.simple_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016com.example.v1B\013SimpleProtoP\001Z\030gen/example/v1;examplev1\242\002\003EXX\252\002\nExample.V1\312\002\nExample\\V1\342\002\026Example\\V1\\GPBMetadata\352\002\013Example::V1'
  _globals['_BAR']._serialized_start=132
  _globals['_BAR']._serialized_end=171
  _globals['_FOO']._serialized_start=69
  _globals['_FOO']._serialized_end=130
# @@protoc_insertion_point(module_scope)
