# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/v1/singular.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x65xample/v1/singular.proto\x12\nexample.v1\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xd1\x03\n\x08Singular\x12\x17\n\x07the_str\x18\x01 \x01(\tR\x06theStr\x12\x17\n\x07the_int\x18\x02 \x01(\x03R\x06theInt\x12\x1d\n\nthe_double\x18\x03 \x01(\x01R\ttheDouble\x12+\n\x08the_enum\x18\x04 \x01(\x0e\x32\x10.example.v1.Wat3R\x07theEnum\x12+\n\x07the_msg\x18\x05 \x01(\x0b\x32\x12.example.v1.Thing3R\x06theMsg\x12\x35\n\x08the_null\x18\x06 \x01(\x0e\x32\x1a.google.protobuf.NullValueR\x07theNull\x12?\n\rthe_timestamp\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0ctheTimestamp\x12;\n\x0bthe_wrapper\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.BoolValueR\ntheWrapper\x12\x36\n\nthe_struct\x18\t \x01(\x0b\x32\x17.google.protobuf.StructR\ttheStruct\x12-\n\x07the_any\x18\n \x01(\x0b\x32\x14.google.protobuf.AnyR\x06theAny\"\x1a\n\x06Thing3\x12\x10\n\x03wat\x18\x02 \x01(\x03R\x03wat**\n\x04Wat3\x12\x14\n\x10WAT3_UNSPECIFIED\x10\x00\x12\x0c\n\x08WAT3_WAT\x10\x01\x42\x82\x01\n\x0e\x63om.example.v1B\rSingularProtoP\x01Z\x18gen/example/v1;examplev1\xa2\x02\x03\x45XX\xaa\x02\nExample.V1\xca\x02\nExample\\V1\xe2\x02\x16\x45xample\\V1\\GPBMetadata\xea\x02\x0b\x45xample::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.v1.singular_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016com.example.v1B\rSingularProtoP\001Z\030gen/example/v1;examplev1\242\002\003EXX\252\002\nExample.V1\312\002\nExample\\V1\342\002\026Example\\V1\\GPBMetadata\352\002\013Example::V1'
  _globals['_WAT3']._serialized_start=659
  _globals['_WAT3']._serialized_end=701
  _globals['_SINGULAR']._serialized_start=164
  _globals['_SINGULAR']._serialized_end=629
  _globals['_THING3']._serialized_start=631
  _globals['_THING3']._serialized_end=657
# @@protoc_insertion_point(module_scope)
