// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrimitiveKind-0]
	_ = x[MessageKind-1]
	_ = x[EnumKind-2]
	_ = x[AnyKind-3]
	_ = x[TimestampKind-4]
	_ = x[WrapperKind-5]
	_ = x[StructKind-6]
	_ = x[NullValueKind-7]
}

const _Kind_name = "PrimitiveKindMessageKindEnumKindAnyKindTimestampKindWrapperKindStructKindNullValueKind"

var _Kind_index = [...]uint8{0, 13, 24, 32, 39, 52, 63, 73, 86}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
