// Code generated by "stringer -type=RepeatKind"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SingularKind-0]
	_ = x[RepeatedKind-1]
	_ = x[MapKind-2]
	_ = x[OneOfKind-3]
}

const _RepeatKind_name = "SingularKindRepeatedKindMapKindOneOfKind"

var _RepeatKind_index = [...]uint8{0, 12, 24, 31, 40}

func (i RepeatKind) String() string {
	if i < 0 || i >= RepeatKind(len(_RepeatKind_index)-1) {
		return "RepeatKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RepeatKind_name[_RepeatKind_index[i]:_RepeatKind_index[i+1]]
}
