// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: example/other/v1/other.proto

package otherv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OtherEnum int32

const (
	OtherEnum_OTHER_ENUM_NA  OtherEnum = 0
	OtherEnum_OTHER_ENUM_WAT OtherEnum = 1
)

// Enum value maps for OtherEnum.
var (
	OtherEnum_name = map[int32]string{
		0: "OTHER_ENUM_NA",
		1: "OTHER_ENUM_WAT",
	}
	OtherEnum_value = map[string]int32{
		"OTHER_ENUM_NA":  0,
		"OTHER_ENUM_WAT": 1,
	}
)

func (x OtherEnum) Enum() *OtherEnum {
	p := new(OtherEnum)
	*p = x
	return p
}

func (x OtherEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtherEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_example_other_v1_other_proto_enumTypes[0].Descriptor()
}

func (OtherEnum) Type() protoreflect.EnumType {
	return &file_example_other_v1_other_proto_enumTypes[0]
}

func (x OtherEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OtherEnum.Descriptor instead.
func (OtherEnum) EnumDescriptor() ([]byte, []int) {
	return file_example_other_v1_other_proto_rawDescGZIP(), []int{0}
}

type Other struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wat int64 `protobuf:"varint,1,opt,name=wat,proto3" json:"wat,omitempty"`
}

func (x *Other) Reset() {
	*x = Other{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_other_v1_other_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Other) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Other) ProtoMessage() {}

func (x *Other) ProtoReflect() protoreflect.Message {
	mi := &file_example_other_v1_other_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Other.ProtoReflect.Descriptor instead.
func (*Other) Descriptor() ([]byte, []int) {
	return file_example_other_v1_other_proto_rawDescGZIP(), []int{0}
}

func (x *Other) GetWat() int64 {
	if x != nil {
		return x.Wat
	}
	return 0
}

var File_example_other_v1_other_proto protoreflect.FileDescriptor

var file_example_other_v1_other_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x2f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x22, 0x19, 0x0a, 0x05, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x61, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x77, 0x61, 0x74, 0x2a, 0x32, 0x0a, 0x09, 0x4f,
	0x74, 0x68, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x54, 0x48, 0x45,
	0x52, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x4e, 0x41, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4f,
	0x54, 0x48, 0x45, 0x52, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x57, 0x41, 0x54, 0x10, 0x01, 0x42,
	0xa2, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x6f, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1c, 0x67, 0x65, 0x6e, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x45, 0x4f, 0x58, 0xaa, 0x02, 0x10, 0x45, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10,
	0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5c, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x5c, 0x56, 0x31,
	0xe2, 0x02, 0x1c, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5c, 0x4f, 0x74, 0x68, 0x65, 0x72,
	0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x12, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x3a, 0x3a, 0x4f, 0x74, 0x68, 0x65, 0x72,
	0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_example_other_v1_other_proto_rawDescOnce sync.Once
	file_example_other_v1_other_proto_rawDescData = file_example_other_v1_other_proto_rawDesc
)

func file_example_other_v1_other_proto_rawDescGZIP() []byte {
	file_example_other_v1_other_proto_rawDescOnce.Do(func() {
		file_example_other_v1_other_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_other_v1_other_proto_rawDescData)
	})
	return file_example_other_v1_other_proto_rawDescData
}

var file_example_other_v1_other_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_other_v1_other_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_example_other_v1_other_proto_goTypes = []interface{}{
	(OtherEnum)(0), // 0: example.other.v1.OtherEnum
	(*Other)(nil),  // 1: example.other.v1.Other
}
var file_example_other_v1_other_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_other_v1_other_proto_init() }
func file_example_other_v1_other_proto_init() {
	if File_example_other_v1_other_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_other_v1_other_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Other); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_other_v1_other_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_other_v1_other_proto_goTypes,
		DependencyIndexes: file_example_other_v1_other_proto_depIdxs,
		EnumInfos:         file_example_other_v1_other_proto_enumTypes,
		MessageInfos:      file_example_other_v1_other_proto_msgTypes,
	}.Build()
	File_example_other_v1_other_proto = out.File
	file_example_other_v1_other_proto_rawDesc = nil
	file_example_other_v1_other_proto_goTypes = nil
	file_example_other_v1_other_proto_depIdxs = nil
}
