# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/other/v1/other.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65xample/other/v1/other.proto\x12\x10\x65xample.other.v1\"\x19\n\x05Other\x12\x10\n\x03wat\x18\x01 \x01(\x03R\x03wat*2\n\tOtherEnum\x12\x11\n\rOTHER_ENUM_NA\x10\x00\x12\x12\n\x0eOTHER_ENUM_WAT\x10\x01\x42\xa2\x01\n\x14\x63om.example.other.v1B\nOtherProtoP\x01Z\x1cgen/example/other/v1;otherv1\xa2\x02\x03\x45OX\xaa\x02\x10\x45xample.Other.V1\xca\x02\x10\x45xample\\Other\\V1\xe2\x02\x1c\x45xample\\Other\\V1\\GPBMetadata\xea\x02\x12\x45xample::Other::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.other.v1.other_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024com.example.other.v1B\nOtherProtoP\001Z\034gen/example/other/v1;otherv1\242\002\003EOX\252\002\020Example.Other.V1\312\002\020Example\\Other\\V1\342\002\034Example\\Other\\V1\\GPBMetadata\352\002\022Example::Other::V1'
  _globals['_OTHERENUM']._serialized_start=77
  _globals['_OTHERENUM']._serialized_end=127
  _globals['_OTHER']._serialized_start=50
  _globals['_OTHER']._serialized_end=75
# @@protoc_insertion_point(module_scope)
